// <auto-generated />
using System;
using GraphqlApiEsay.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphqlApiEsay.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphqlApiEsay.Models.CarnePescado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlergenoCarnePescado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCarnePescado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarnePescado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlergenoCarnePescado = true,
                            NombreCarnePescado = "Pescado"
                        },
                        new
                        {
                            Id = 2,
                            AlergenoCarnePescado = true,
                            NombreCarnePescado = "Crustáceos"
                        },
                        new
                        {
                            Id = 3,
                            AlergenoCarnePescado = false,
                            NombreCarnePescado = "Filete"
                        },
                        new
                        {
                            Id = 4,
                            AlergenoCarnePescado = true,
                            NombreCarnePescado = "Molusco"
                        },
                        new
                        {
                            Id = 5,
                            AlergenoCarnePescado = false,
                            NombreCarnePescado = "Chorizo"
                        },
                        new
                        {
                            Id = 6,
                            AlergenoCarnePescado = false,
                            NombreCarnePescado = "Carne de Cerdo"
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.HarinaCereal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlergenoHarina")
                        .HasColumnType("bit");

                    b.Property<string>("NombreHarina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HarinaCereales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlergenoHarina = true,
                            NombreHarina = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            AlergenoHarina = true,
                            NombreHarina = "Harina de trigo"
                        },
                        new
                        {
                            Id = 3,
                            AlergenoHarina = false,
                            NombreHarina = "Cereales"
                        },
                        new
                        {
                            Id = 4,
                            AlergenoHarina = true,
                            NombreHarina = "Pan Rallado"
                        },
                        new
                        {
                            Id = 5,
                            AlergenoHarina = false,
                            NombreHarina = "Harina de trigo sin gluten"
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.Lacteo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlergenoLacteo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreLacteo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lacteos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlergenoLacteo = true,
                            NombreLacteo = "Leche"
                        },
                        new
                        {
                            Id = 2,
                            AlergenoLacteo = true,
                            NombreLacteo = "Huevos"
                        },
                        new
                        {
                            Id = 3,
                            AlergenoLacteo = true,
                            NombreLacteo = "Yogur"
                        },
                        new
                        {
                            Id = 4,
                            AlergenoLacteo = false,
                            NombreLacteo = "Leche sin lactosa"
                        },
                        new
                        {
                            Id = 5,
                            AlergenoLacteo = false,
                            NombreLacteo = "Leche de almendra"
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombrePlato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombrePlato = "Canelones con Bechamel"
                        },
                        new
                        {
                            Id = 2,
                            NombrePlato = "Merluza a la romana"
                        },
                        new
                        {
                            Id = 3,
                            NombrePlato = "Filete a la plancha"
                        },
                        new
                        {
                            Id = 4,
                            NombrePlato = "Lentejas con Chorizo"
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.PlatoIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HarinaId")
                        .HasColumnType("int");

                    b.Property<int?>("LacteoId")
                        .HasColumnType("int");

                    b.Property<bool>("ModificadoPlato")
                        .HasColumnType("bit");

                    b.Property<int>("PlatoId")
                        .HasColumnType("int");

                    b.Property<int?>("VerduraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarneId");

                    b.HasIndex("HarinaId");

                    b.HasIndex("LacteoId");

                    b.HasIndex("PlatoId");

                    b.HasIndex("VerduraId");

                    b.ToTable("PlatoIngredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarneId = 6,
                            FechaModificado = new DateTime(2021, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HarinaId = 2,
                            LacteoId = 2,
                            ModificadoPlato = false,
                            PlatoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarneId = 1,
                            FechaModificado = new DateTime(2021, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HarinaId = 2,
                            LacteoId = 2,
                            ModificadoPlato = false,
                            PlatoId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarneId = 6,
                            FechaModificado = new DateTime(2021, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModificadoPlato = false,
                            PlatoId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarneId = 5,
                            FechaModificado = new DateTime(2021, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModificadoPlato = false,
                            PlatoId = 4,
                            VerduraId = 9
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.VerduraFruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlergenoVerdura")
                        .HasColumnType("bit");

                    b.Property<string>("NombreVerdura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerduraFrutas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlergenoVerdura = true,
                            NombreVerdura = "Soja"
                        },
                        new
                        {
                            Id = 2,
                            AlergenoVerdura = true,
                            NombreVerdura = "Almendras"
                        },
                        new
                        {
                            Id = 3,
                            AlergenoVerdura = true,
                            NombreVerdura = "Avellanas"
                        },
                        new
                        {
                            Id = 4,
                            AlergenoVerdura = true,
                            NombreVerdura = "Apio"
                        },
                        new
                        {
                            Id = 5,
                            AlergenoVerdura = true,
                            NombreVerdura = "Sésamo"
                        },
                        new
                        {
                            Id = 6,
                            AlergenoVerdura = true,
                            NombreVerdura = "Mostaza"
                        },
                        new
                        {
                            Id = 7,
                            AlergenoVerdura = true,
                            NombreVerdura = "Altramuces"
                        },
                        new
                        {
                            Id = 8,
                            AlergenoVerdura = false,
                            NombreVerdura = "Lechuga"
                        },
                        new
                        {
                            Id = 9,
                            AlergenoVerdura = false,
                            NombreVerdura = "Lentejas"
                        });
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.PlatoIngrediente", b =>
                {
                    b.HasOne("GraphqlApiEsay.Models.CarnePescado", "CarnePescado")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("CarneId");

                    b.HasOne("GraphqlApiEsay.Models.HarinaCereal", "HarinaCereal")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("HarinaId");

                    b.HasOne("GraphqlApiEsay.Models.Lacteo", "Lacteo")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("LacteoId");

                    b.HasOne("GraphqlApiEsay.Models.Plato", "Plato")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphqlApiEsay.Models.VerduraFruta", "VerduraFruta")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("VerduraId");

                    b.Navigation("CarnePescado");

                    b.Navigation("HarinaCereal");

                    b.Navigation("Lacteo");

                    b.Navigation("Plato");

                    b.Navigation("VerduraFruta");
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.CarnePescado", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.HarinaCereal", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.Lacteo", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.Plato", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("GraphqlApiEsay.Models.VerduraFruta", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
